version: '2'

services:

  web:
    build: ./wordpress
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=password
    volumes:
      - ./wordpress/content-htaccess:/var/www/html/wp-content/.htaccess
      - ./wordpress-theme/:/var/www/html/wp-content/themes/sarahtherad/
      - ./dist/assets/sarahtherad.css:/var/www/html/wp-content/themes/sarahtherad/style.css

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      - MYSQL_ROOT_PASSWORD=password
